name: Build bundle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bundle Component with Vite
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: |
          npm ci
          npm run build --if-present
          mv dist omnis-echarts
          tar -zcvf omnis-echarts.tar.gz omnis-echarts/
      - name: Create Omnis Studio HTML Control
        uses: actions/upload-artifact@v3
        with:
          name: omnis-echarts
          path: omnis-echarts.tar.gz
      - name: get-npm-version
        if: startsWith(github.ref, 'refs/tags/')
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.package-version.outputs.current-version }}
          tag_name: ${{ github.ref }}
      - name: upload HTML Control artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./omnis-echarts.tar.gz
          asset_name: omnis-echarts.tar.gz
          asset_content_type: application/gzip
