name: Build bundle

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: mv dist omnis-echarts
      - name: Create Omnis Studio HTML Control
        uses: actions/upload-artifact@v3
        with:
          name: omnis-control
          path: |
            omnis-echarts
